version: '3.7'

services:
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3308:3306/tcp'
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: repositories
      MYSQL_USER: root
      MYSQL_PASSWORD:

  todo-app-backend:
    depends_on:
      - db
    build:
      context: ../stream-referential-back
    volumes:
      - '${CONFIGURATION}:/var/lib/load/back/configuration'
      - '${DATA}:/data'

volumes:
  db_data: {}

networks:
  default:
    name: stream-referential-network