version: '3.7'

services:

  stream-referential-db:
    container_name: stream-referential-db
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3308:3306/tcp'
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: repositories
      MYSQL_USER: root
      MYSQL_PASSWORD:

  stream-referential-www:
    depends_on:
      - stream-referential-db
    build:
      context: ../stream-referential-www
    ports:
      - '8181:8181/tcp'
    command: bash -c "/wait && cd /app && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8181"
    environment:
      - WAIT_HOSTS=stream-referential-db:3306
      - APP_KEY
      - APP_DEBUG
      - APP_URL
      - DB_HOST
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD

  stream-referential-back:
    depends_on:
      - stream-referential-db
    build:
      context: ../stream-referential-back
    volumes:
      - '${CONFIGURATION}:/var/lib/load/back/configuration'
      - '${DATA}:/data'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://stream-referential-db/repositories?serverTimezone=Europe/Paris&useCompression=true&allowMultiQueries=true
      - WAIT_HOSTS=stream-referential-db:3306

volumes:
  db_data: {}

networks:
  default:
    name: stream-referential-network